import { PrismaClient, TicketStatus, TicketCategory, TicketSource } from '@prisma/client';

const prisma = new PrismaClient();

const daysAgo = (d: number) => new Date(Date.now() - d * 24 * 60 * 60 * 1000);

const tickets: Array<{
  subject: string;
  body: string;
  fromName: string;
  fromEmail: string;
  status: TicketStatus;
  category: TicketCategory;
  source: TicketSource;
  aiClassified: boolean;
  createdAt: Date;
}> = [
  // TECHNICAL_QUESTION
  { subject: 'App crashes on iOS 17 after latest update', body: 'Hi, ever since I updated to your app version 4.2.1 on my iPhone 15, the app crashes immediately on launch. I tried reinstalling but the problem persists. Please help.', fromName: 'Aiden Clarke', fromEmail: 'aiden.clarke@gmail.com', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(1) },
  { subject: 'Two-factor authentication not sending SMS', body: "I enabled 2FA on my account but I'm not receiving the SMS code. I've verified my phone number is correct. My carrier is Verizon. Can you help?", fromName: 'Sofia Reyes', fromEmail: 'sofia.reyes@outlook.com', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(2) },
  { subject: 'Webhook events not firing for order.completed', body: "We have a webhook set up for order.completed events but they stopped firing 3 days ago. Other events like order.created still work. We haven't changed anything on our end.", fromName: 'Dev Team - Shopify Plus', fromEmail: 'devops@retailhub.com', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(1) },
  { subject: 'CSV export is missing columns', body: 'When I export my reports to CSV, the "tags" and "custom_fields" columns are missing. They were present last month. This is affecting our reporting pipeline.', fromName: 'Marcus Lee', fromEmail: 'marcus.lee@dataflow.co', status: 'RESOLVED', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(10) },
  { subject: 'Search returns no results after reindexing', body: 'We triggered a full reindex yesterday and now search returns zero results for all queries. The index shows 50,000 documents but search is broken. Urgent — production issue.', fromName: 'Priyanka Nair', fromEmail: 'p.nair@searchlabs.io', status: 'RESOLVED', category: 'TECHNICAL_QUESTION', source: 'MANUAL', aiClassified: true, createdAt: daysAgo(5) },
  { subject: 'OAuth redirect URI mismatch error', body: "Getting 'redirect_uri_mismatch' when authenticating with Google OAuth. I've set the redirect URI to https://app.mysite.com/auth/callback in both your dashboard and Google Console.", fromName: 'Ben Fowler', fromEmail: 'ben@mysite.com', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(0) },
  { subject: 'Can\'t upload files larger than 10MB', body: 'File uploads fail silently for anything over 10MB. The progress bar reaches 100% then the file never appears. No error is shown. Our plan supposedly supports up to 100MB uploads.', fromName: 'Chloé Martin', fromEmail: 'chloe.martin@mediahouse.fr', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(3) },
  { subject: 'SMTP integration not sending from custom domain', body: 'I configured SMTP with our custom domain mail.ourcompany.com but emails are still going out from your default domain. SPF and DKIM records are all set correctly.', fromName: 'James Wu', fromEmail: 'james@ourcompany.com', status: 'CLOSED', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(20) },
  { subject: 'API authentication fails with valid token', body: 'Our API token is valid (not expired, correct permissions) but every request returns 401 Unauthorized. This started happening after we rotated the token yesterday.', fromName: 'Isabel Santos', fromEmail: 'isabel.santos@fintech.pt', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'MANUAL', aiClassified: true, createdAt: daysAgo(1) },
  { subject: 'Database connection timeout in EU region', body: "We're seeing frequent connection timeouts to our EU database instance. Average latency jumped from 20ms to 4000ms. Our app is hosted in eu-west-1. Is there an infrastructure issue?", fromName: 'Lukas Bauer', fromEmail: 'lukas.bauer@cloudapp.de', status: 'RESOLVED', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(8) },
  { subject: 'Push notifications not delivered on Android', body: "Push notifications work on iOS but Android users aren't receiving them. We're using Firebase Cloud Messaging. This affects about 40% of our user base.", fromName: 'Yuki Tanaka', fromEmail: 'yuki.t@mobileapp.jp', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(2) },
  { subject: 'Pagination returning duplicate records', body: "When paginating through results using cursor-based pagination, we're getting duplicate records at page boundaries. This happens consistently when the dataset has recently changed.", fromName: 'Natasha Ivanova', fromEmail: 'n.ivanova@techstartup.ru', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'MANUAL', aiClassified: true, createdAt: daysAgo(4) },
  { subject: 'SSL certificate error on custom subdomain', body: "We added a custom subdomain help.ourbrand.com but it shows an SSL certificate error in browsers. The domain is pointing correctly via CNAME. The certificate says it's for your domain, not ours.", fromName: 'Arjun Mehta', fromEmail: 'arjun@ourbrand.in', status: 'CLOSED', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(15) },
  { subject: 'Bulk import stuck at 0% for 2 hours', body: 'I started a bulk import of 20,000 contacts 2 hours ago and the progress bar is still at 0%. The job shows as "running" in the dashboard. Should I cancel and retry?', fromName: 'Grace O\'Brien', fromEmail: 'grace.obrien@salesforce-user.ie', status: 'RESOLVED', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(6) },
  { subject: 'Embed script causing console errors', body: 'After adding your embed script to our website, the browser console shows: "Uncaught TypeError: Cannot read properties of null (reading \'appendChild\')". This happens on all pages.', fromName: 'Daniel Kim', fromEmail: 'd.kim@webagency.kr', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(1) },

  // REFUND_REQUEST
  { subject: 'Charged after cancelling subscription', body: "I cancelled my subscription on June 1st and received a confirmation email, but I was still charged on June 15th. Please refund $89 to my card ending in 4242.", fromName: 'Emma Thompson', fromEmail: 'emma.t@personalmail.co.uk', status: 'OPEN', category: 'REFUND_REQUEST', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(3) },
  { subject: 'Wrong plan charged — signed up for Starter not Pro', body: 'I selected the Starter plan ($19/month) during signup but my card was charged $79 for the Pro plan. Order #ORD-99201. Please correct and refund the difference.', fromName: 'Tomás García', fromEmail: 'tomas.garcia@empresa.es', status: 'RESOLVED', category: 'REFUND_REQUEST', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(12) },
  { subject: 'Annual plan refund — feature not as advertised', body: "I purchased the annual plan based on the landing page which advertised unlimited exports. After purchasing I found exports are capped at 1000/month. This is misleading. I'd like a full refund.", fromName: 'Rachel Green', fromEmail: 'rachel.g@freelancer.net', status: 'OPEN', category: 'REFUND_REQUEST', source: 'MANUAL', aiClassified: true, createdAt: daysAgo(2) },
  { subject: 'Duplicate charge on renewal', body: 'My subscription renewed on the 10th and I see two identical charges of $49 on my bank statement. Please refund one of them. Transaction IDs: TXN-44521 and TXN-44523.', fromName: 'Oliver Müller', fromEmail: 'o.muller@private.de', status: 'RESOLVED', category: 'REFUND_REQUEST', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(9) },
  { subject: 'Team plan refund — employee left company', body: "We're paying for 10 seats but one employee left and we'd like to remove their seat and get a pro-rated refund for the 8 months remaining on their annual seat.", fromName: 'HR Manager - Brightworks', fromEmail: 'hr@brightworks.com', status: 'CLOSED', category: 'REFUND_REQUEST', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(30) },
  { subject: "Refund request — couldn't use service due to outage", body: 'Your service was down for 18 hours last month (Nov 3–4). During that time we lost business. Per your SLA, I would like a credit or refund for the downtime. Account: enterprise@corp.com', fromName: 'VP Engineering - Corp', fromEmail: 'enterprise@corp.com', status: 'RESOLVED', category: 'REFUND_REQUEST', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(20) },
  { subject: 'Accidental upgrade — please downgrade and refund', body: 'I accidentally clicked upgrade to Business plan. I need to stay on Professional. Please downgrade my account and refund the difference of $110 charged 2 days ago.', fromName: 'Mei Chen', fromEmail: 'mei.chen@startup.sg', status: 'OPEN', category: 'REFUND_REQUEST', source: 'MANUAL', aiClassified: false, createdAt: daysAgo(2) },
  { subject: '30-day refund request — not satisfied with product', body: "I've been using the product for 25 days and it doesn't meet my needs. I'd like to exercise the 30-day money-back guarantee. Order #ORD-78854 dated June 1st.", fromName: 'Peter Walsh', fromEmail: 'peter.walsh@consultancy.ie', status: 'OPEN', category: 'REFUND_REQUEST', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(1) },
  { subject: 'Charged in USD instead of GBP', body: 'I am based in the UK and your website showed prices in GBP, but I was charged in USD. The exchange rate difference cost me an extra £12. Please refund the currency difference.', fromName: 'Sarah Hobbs', fromEmail: 'sarah.hobbs@london.co.uk', status: 'RESOLVED', category: 'REFUND_REQUEST', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(14) },
  { subject: 'Refund for unused add-on', body: 'I purchased the Advanced Analytics add-on 2 months ago but never used it — I realized it duplicates a feature I already have. Can I get a refund for the remaining subscription period?', fromName: 'Carlos Mendez', fromEmail: 'carlos.m@latam-co.mx', status: 'CLOSED', category: 'REFUND_REQUEST', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(45) },
  { subject: "Payment failed but I'm still charged", body: 'My payment method failed at checkout (I saw an error) but my bank shows a charge of $199. I never got access to the account. Please refund immediately.', fromName: 'Fatima Al-Hassan', fromEmail: 'fatima.alhassan@webmail.ae', status: 'OPEN', category: 'REFUND_REQUEST', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(0) },

  // GENERAL_QUESTION
  { subject: 'How to export data before account deletion', body: "I'm planning to close my account. Can you tell me how to export all my data (contacts, notes, files) before I delete it? I want to make sure I don't lose anything.", fromName: 'Nina Johansson', fromEmail: 'nina.j@personal.se', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(7) },
  { subject: 'What\'s the difference between Admin and Agent roles?', body: 'We are setting up our team and I need to understand the permissions difference between Admin and Agent roles before assigning them. Can you explain what each can and cannot do?', fromName: 'Ravi Patel', fromEmail: 'ravi.patel@teamlead.in', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'MANUAL', aiClassified: false, createdAt: daysAgo(3) },
  { subject: 'Can I use the API without a paid plan?', body: "I'm a developer evaluating your product. Does the free tier include API access? If so, what are the rate limits? I want to prototype before committing to a paid plan.", fromName: 'Chris Novak', fromEmail: 'chris@devproject.cz', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(5) },
  { subject: 'Do you offer discounts for non-profits?', body: 'We are a registered non-profit organization. Do you offer any discounted or free plans for NGOs? We have a small team of 5 and limited budget.', fromName: 'Amara Diallo', fromEmail: 'amara@ngo-africa.org', status: 'OPEN', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(4) },
  { subject: 'How long is data retained after account deletion?', body: "If I delete my account today, how long do you retain my data? I need to know for GDPR compliance purposes. Is there any way to request immediate deletion?", fromName: 'François Dubois', fromEmail: 'f.dubois@dpo-consult.fr', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(18) },
  { subject: 'Can I change my billing cycle from monthly to annual?', body: "I'm currently on a monthly plan and want to switch to annual to save money. Will this take effect immediately or at my next billing date? And will I lose any current data or settings?", fromName: 'Helen Park', fromEmail: 'helen.park@smb.kr', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(11) },
  { subject: 'Is there a mobile app available?', body: 'I mostly work from my phone. Is there a native mobile app for iOS and Android, or is the product only accessible via web browser? If mobile, where can I download it?', fromName: 'Andre Ferreira', fromEmail: 'andre.f@mobile-first.br', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'MANUAL', aiClassified: false, createdAt: daysAgo(6) },
  { subject: 'Do you support HIPAA compliance?', body: 'We work in healthcare and need to ensure any tools we use are HIPAA compliant. Do you offer a BAA (Business Associate Agreement)? Is your platform HIPAA certified?', fromName: 'Dr. Patricia Kim', fromEmail: 'p.kim@healthtech.us', status: 'OPEN', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(2) },
  { subject: 'How to transfer account ownership', body: "Our CTO who created the account is leaving the company. How do we transfer account ownership to our new CTO? We don't want to lose any data or settings.", fromName: 'Ops Manager - BuildCo', fromEmail: 'ops@buildco.com', status: 'OPEN', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(1) },
  { subject: 'Is there an uptime SLA for the Enterprise plan?', body: "We're evaluating your Enterprise plan. Does it include an SLA with guaranteed uptime? We need at least 99.9% uptime for our production workloads. Can you share the SLA document?", fromName: 'Contracts - MegaCorp', fromEmail: 'contracts@megacorp.com', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(22) },
  { subject: 'How to add a custom email domain for notifications', body: 'Emails are sent from your default domain. We want customer-facing emails to come from support@ourcompany.com. How do I configure a custom sender domain?', fromName: 'IT Admin - OurCompany', fromEmail: 'itadmin@ourcompany.com', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(9) },
  { subject: 'Can multiple users share a single account?', body: "We're a small team of 3 and want to know if multiple people can be logged in to the same account simultaneously, or if we need separate accounts. We're on the Starter plan.", fromName: 'Tom Bradley', fromEmail: 'tom.b@smallbiz.co.uk', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'MANUAL', aiClassified: false, createdAt: daysAgo(13) },
  { subject: 'What payment methods do you accept?', body: 'I want to subscribe but my company only uses bank transfers (SEPA) or purchase orders. Do you accept these payment methods for annual plans? We cannot use credit cards.', fromName: 'Purchasing - EuropeCo', fromEmail: 'purchasing@europeco.eu', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(16) },
  { subject: 'How to white-label the product for clients', body: "We're an agency and want to resell your product under our brand. Do you offer white-labeling? What does it include and what does it cost? We have about 20 clients interested.", fromName: 'Agency Director - PixelStudio', fromEmail: 'director@pixelstudio.agency', status: 'OPEN', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(3) },
  { subject: 'Need to update billing email address', body: 'Our finance team has a new email address. How do I update the billing contact email so invoices go to the right person? Current billing email: old-finance@company.com', fromName: 'Admin - Company', fromEmail: 'admin@company.com', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(7) },

  // More TECHNICAL_QUESTION
  { subject: 'Automated reports not emailing on schedule', body: "I set up a weekly report to email every Monday at 8am but it's been 3 weeks and no emails have arrived. I've verified the schedule settings are correct and my email address is right.", fromName: 'Patricia Morgan', fromEmail: 'p.morgan@reports-user.com', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(5) },
  { subject: 'Custom domain not propagating after 48 hours', body: "I added a CNAME record for my custom domain 48+ hours ago but the domain still shows 'Not configured' in the dashboard. My DNS provider shows the record is correct.", fromName: 'Website Owner', fromEmail: 'admin@customdomain.com', status: 'RESOLVED', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(7) },
  { subject: 'Zapier integration not triggering on new tickets', body: "My Zapier zap watches for new tickets but stopped triggering 5 days ago. I've reconnected the integration and the test trigger works, but live events aren't coming through.", fromName: 'Operations Lead', fromEmail: 'ops@automations.co', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'MANUAL', aiClassified: true, createdAt: daysAgo(3) },
  { subject: 'Memory leak in client-side SDK', body: "We've identified a memory leak in your JavaScript SDK v3.1.2. When running for >2 hours, memory usage grows continuously. We've isolated it to the event listener in the socket module. Do you have a patch or workaround?", fromName: 'Engineering - Acme Corp', fromEmail: 'eng@acmecorp.com', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(2) },
  { subject: 'Multi-tenant setup — data isolation question', body: "We're building a multi-tenant SaaS on top of your platform. Can you confirm that data is fully isolated per tenant? We need to ensure one tenant can never access another's data.", fromName: 'CTO - MultiSaaS', fromEmail: 'cto@multisaas.io', status: 'RESOLVED', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(25) },
  { subject: 'Intermittent 504 Gateway Timeout on large queries', body: 'Large queries (returning >10,000 records) intermittently return 504 Gateway Timeout. Smaller queries always work. The timeout happens after exactly 30 seconds. Is this a hard limit?', fromName: 'Backend Dev - DataCo', fromEmail: 'backend@dataco.net', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(4) },
  { subject: 'Date formatting incorrect in exported CSV', body: 'Dates in exported CSVs are formatted as MM/DD/YYYY but our systems expect YYYY-MM-DD (ISO 8601). Is there a way to change the date format in exports?', fromName: 'Data Analyst - Finance', fromEmail: 'analyst@financegroup.com', status: 'RESOLVED', category: 'TECHNICAL_QUESTION', source: 'MANUAL', aiClassified: false, createdAt: daysAgo(11) },
  { subject: 'Audit log missing entries for deleted records', body: "The audit log doesn't show who deleted a record — it only shows creates and updates. This is a compliance requirement for us. Is this a known limitation or a bug?", fromName: 'Compliance Officer', fromEmail: 'compliance@regulated-co.com', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(6) },
  { subject: 'Third-party font not loading in white-label portal', body: "We're using a custom white-label portal and our brand font (Inter from Google Fonts) is not loading. The portal falls back to a system font instead. CSP headers might be blocking it.", fromName: 'Brand Manager - WhiteLabel', fromEmail: 'brand@whitelabel-client.com', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(2) },
  { subject: 'Slack integration sending duplicate notifications', body: "The Slack integration is sending 2–3 duplicate notifications for every event. I've checked and there's only one Slack integration configured. Restarting the integration didn't help.", fromName: 'IT Admin - SlackTeam', fromEmail: 'it@slackteam.com', status: 'RESOLVED', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(10) },

  // More REFUND_REQUEST
  { subject: 'Refund for auto-renewal I wasn\'t notified about', body: "My annual subscription auto-renewed for $299 and I received no prior notification email. I would have cancelled if I'd known. Please refund the charge — I no longer need the service.", fromName: 'Maria Santos', fromEmail: 'maria.santos@home.pt', status: 'OPEN', category: 'REFUND_REQUEST', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(1) },
  { subject: 'Partial refund for downgrade mid-cycle', body: "I downgraded from Business to Starter on the 10th of the month. I'm expecting a pro-rated credit for the remaining 20 days of Business but I don't see it on my next invoice.", fromName: 'CFO - SmallBiz', fromEmail: 'cfo@smallbizco.com', status: 'RESOLVED', category: 'REFUND_REQUEST', source: 'MANUAL', aiClassified: false, createdAt: daysAgo(8) },
  { subject: 'Charged $0 then charged full price — refund difference', body: "There was a promo offering 3 months free. I signed up and was charged $0 for month 1, then the full price of $59 in month 2. The promotion should have covered months 1–3.", fromName: 'Wei Zhang', fromEmail: 'wei.zhang@promo-user.cn', status: 'OPEN', category: 'REFUND_REQUEST', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(3) },
  { subject: 'Deceased account holder — please cancel and refund', body: 'My father passed away and had an active subscription with you. I am his daughter and executor. Please cancel the subscription and refund any remaining prepaid period. I can provide documentation.', fromName: 'Estate of John Walker', fromEmail: 'daughter@walker-family.com', status: 'OPEN', category: 'REFUND_REQUEST', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(4) },
  { subject: 'Annual plan charged in error — should be monthly', body: 'I chose monthly billing but was charged the annual price of $588 instead of $59. This was not what I selected during checkout. Please refund and switch to monthly.', fromName: 'Alex Turner', fromEmail: 'alex.turner@creative.co.nz', status: 'RESOLVED', category: 'REFUND_REQUEST', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(14) },

  // More GENERAL_QUESTION
  { subject: 'Do you have a public status page?', body: "Is there a public status page where we can check for outages and incidents? We'd like to subscribe to updates so we're notified when there are issues.", fromName: 'SRE - CloudNative', fromEmail: 'sre@cloudnative.io', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(17) },
  { subject: 'How to integrate with Salesforce CRM', body: "We use Salesforce and want to sync customer data between your platform and Salesforce. Is there a native integration or do we need to use a third-party tool like Zapier?", fromName: 'Sales Ops - Enterprise', fromEmail: 'salesops@enterprise-client.com', status: 'OPEN', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(2) },
  { subject: 'Can I schedule a demo call?', body: "I'm seriously evaluating your Enterprise plan for our company of 500 people. Is it possible to schedule a demo with a sales engineer who can walk us through the product and answer our specific questions?", fromName: 'Director of IT - BigCo', fromEmail: 'it-director@bigco.com', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(19) },
  { subject: 'Password policy requirements', body: "What are the password requirements for user accounts? We're setting up a security audit and need to document the minimum password policy enforced by your system.", fromName: 'Security Auditor', fromEmail: 'audit@securityfirm.com', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'MANUAL', aiClassified: false, createdAt: daysAgo(28) },
  { subject: 'Is chat support available on weekends?', body: "I've tried the live chat feature on a Saturday and Sunday and nobody responds. Is chat support only available on weekdays? What are the support hours for each plan?", fromName: 'Weekend Worker', fromEmail: 'always-online@remote.com', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(21) },
  { subject: 'Feature request — dark mode', body: 'I use the product every day and would really love a dark mode option. My eyes get tired with the current white interface. Is this on the roadmap? Many of my colleagues feel the same.', fromName: 'Daily User', fromEmail: 'daily.user@morning.co', status: 'CLOSED', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(40) },
  { subject: 'How to generate an API key', body: "I've been trying to find where to generate an API key for my account but can't locate it. I've looked in Settings and Developer sections. Can you point me to the right place?", fromName: 'Developer Newbie', fromEmail: 'newdev@learntocode.com', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(5) },
  { subject: 'What is your data center location?', body: "For compliance reasons we need to know where our data is stored. Are your data centers in the EU? We need to ensure GDPR compliance and can only use EU-based storage.", fromName: 'DPO - EU Company', fromEmail: 'dpo@eu-regulated.eu', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(33) },
  { subject: 'Request for W-9 form for tax purposes', body: "Our accounts payable team needs a W-9 form from your company for tax purposes. We cannot process your invoices without it. Can you provide this or direct me to where I can download it?", fromName: 'AP Manager - US Corp', fromEmail: 'ap@uscorp.com', status: 'OPEN', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(1) },
  { subject: 'Do you offer training or onboarding sessions?', body: "We just signed up for the Business plan with 15 users. Do you offer onboarding sessions or training resources to help new teams get started quickly? Video tutorials or a live call would be great.", fromName: 'Team Lead - NewClient', fromEmail: 'teamlead@newclient.com', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(12) },
  { subject: 'How to set up email forwarding for tickets', body: "I want all emails sent to support@mycompany.com to automatically create tickets. How do I configure email forwarding? What email address do I forward to?", fromName: 'IT Manager - MyCompany', fromEmail: 'it.manager@mycompany.com', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'MANUAL', aiClassified: true, createdAt: daysAgo(9) },

  // More mixed
  { subject: 'Import from Zendesk — how to migrate data', body: "We're switching from Zendesk. Do you have a migration tool or guide for importing tickets, customers, and history from Zendesk? We have 5 years of data.", fromName: 'Support Manager - Migration', fromEmail: 'support.mgr@migrating-co.com', status: 'OPEN', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(2) },
  { subject: 'Rate limit on free tier is too low', body: "The free tier only allows 100 API calls per day which is not enough even for testing. Is there any way to get a temporary increase for development purposes? We plan to upgrade once we launch.", fromName: 'Startup Dev', fromEmail: 'dev@earlystagestartup.com', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(3) },
  { subject: 'Account locked after too many login attempts', body: "My account got locked after forgetting my password. I've reset the password via email but still can't log in — it says the account is locked. How do I unlock it?", fromName: 'Confused User', fromEmail: 'confused.user@mailbox.com', status: 'RESOLVED', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(6) },
  { subject: 'Request invoice with company VAT number', body: "Our last 3 invoices don't include our VAT number (EU123456789). We need this for our accounting. How do I add our VAT number to the account so future invoices include it?", fromName: 'Finance - EU Business', fromEmail: 'finance@eubusiness.eu', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(15) },
  { subject: 'Can\'t delete a record — permission error', body: "I'm an Admin but when I try to delete certain records I get a permission error: 'Insufficient permissions to perform this action.' Why would an Admin not be able to delete a record?", fromName: 'Admin User', fromEmail: 'admin.user@puzzled.com', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'MANUAL', aiClassified: true, createdAt: daysAgo(1) },
  { subject: 'Trial expired — can I get an extension?', body: "My 14-day trial expired yesterday. I was in the middle of evaluating with my team and we need 2 more weeks. Is it possible to get a trial extension? We are serious buyers.", fromName: 'Evaluator - PotentialClient', fromEmail: 'evaluator@potentialclient.com', status: 'OPEN', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(1) },
  { subject: 'Emails landing in spam despite SPF/DKIM setup', body: "Emails sent from your platform to our customers are landing in spam despite correct SPF and DKIM records. We've verified with MXToolbox. The issue started last week.", fromName: 'Email Admin - Campaign Co', fromEmail: 'email.admin@campaignco.com', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(4) },
  { subject: 'How to downgrade to free plan without losing data', body: "I need to temporarily downgrade to the free plan due to budget constraints. If I downgrade, will I lose my data and configurations? Can I upgrade back later and restore everything?", fromName: 'Budget Conscious User', fromEmail: 'budget@personalproject.com', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(8) },
  { subject: 'Refund — purchased wrong add-on by mistake', body: "I accidentally purchased the 'Premium Support' add-on instead of 'Advanced Analytics'. I clicked the wrong button. It was charged 10 minutes ago. Please refund $49 and cancel the add-on.", fromName: 'Quick Mistake User', fromEmail: 'quick.mistake@company.com', status: 'RESOLVED', category: 'REFUND_REQUEST', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(3) },
  { subject: 'GraphQL subscription not receiving real-time events', body: "We're using your GraphQL API with subscriptions for real-time updates. The subscription connects successfully but no events are pushed. REST polling works fine. Using Apollo Client v3.", fromName: 'GraphQL Dev', fromEmail: 'graphql.dev@modernstack.com', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'MANUAL', aiClassified: true, createdAt: daysAgo(2) },
  { subject: 'Can I pause my subscription instead of cancelling?', body: "I'm going on maternity leave for 3 months and won't be using the service. Is there an option to pause billing and resume later without losing my data and settings?", fromName: 'Laura Mitchell', fromEmail: 'laura.mitchell@homemail.com', status: 'OPEN', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(1) },
  { subject: 'Two accounts merged — missing historical data', body: "We requested account merges last week and it went through, but historical tickets and notes from the secondary account are missing. Can you check if the data was migrated correctly?", fromName: 'Account Manager - Fusion Co', fromEmail: 'accounts@fusionco.com', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(3) },
  { subject: 'Need to add a second admin to our account', body: "I am the sole admin and want to add my co-founder as a second admin. I can see how to add agents but not admins. Is there a way to promote an existing user to admin?", fromName: 'Co-Founder - Duo Startup', fromEmail: 'founder@duostartup.com', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(5) },
  { subject: 'Report showing incorrect date range', body: "The monthly report for June shows data from May 28 to June 27 instead of June 1 to June 30. Is the report using rolling 30 days instead of calendar month? How do I change this?", fromName: 'Analytics User', fromEmail: 'analytics@reportingco.com', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'MANUAL', aiClassified: true, createdAt: daysAgo(2) },
  { subject: 'Refund for failed payment that was retried and charged', body: "My payment failed on the 1st. I updated my card on the 5th and it was charged successfully. But I also see the original failed attempt charged $0 then re-attempted and charged full price. One charge seems duplicate.", fromName: 'Billing Confused', fromEmail: 'billing.confused@mailbox.net', status: 'RESOLVED', category: 'REFUND_REQUEST', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(7) },
  { subject: 'Integration with Microsoft Teams', body: "Do you have a native Microsoft Teams integration? We want notifications and updates to appear in our Teams channels. I can see Slack integration but nothing for Teams.", fromName: 'IT Admin - Enterprise365', fromEmail: 'it.admin@enterprise365.com', status: 'OPEN', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(1) },
  { subject: 'Session timeout too short — logging out every 15 minutes', body: "The session expires after 15 minutes of inactivity which is very disruptive. Is there a setting to increase the session timeout? We'd prefer at least 4 hours.", fromName: 'Power User - Always Working', fromEmail: 'poweruser@busyteam.com', status: 'RESOLVED', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(9) },
  { subject: 'Forgot to apply coupon code at checkout — can it be applied retroactively?', body: "I just signed up and paid but forgot to enter my coupon code SAVE30. Can the discount be applied to my first invoice retroactively, or issued as a credit?", fromName: 'New Subscriber', fromEmail: 'new.subscriber@signup.com', status: 'OPEN', category: 'REFUND_REQUEST', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(0) },
  { subject: 'Image attachments not showing in ticket replies', body: "When customers reply via email with image attachments, the images don't appear in the ticket thread — only the text comes through. PDFs work fine. Is there a file type restriction?", fromName: 'Support Lead - ImageCo', fromEmail: 'support.lead@imageco.com', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(4) },
  { subject: 'How to restrict agent access to specific ticket categories', body: "We want agents to only see tickets in their assigned category (e.g. billing agents only see billing tickets). Is there a way to set category-based permissions or views for agents?", fromName: 'Operations Manager', fromEmail: 'ops.manager@scaledteam.com', status: 'OPEN', category: 'GENERAL_QUESTION', source: 'MANUAL', aiClassified: false, createdAt: daysAgo(2) },
  { subject: 'Ticket auto-close not working after 7 days', body: "I configured tickets to auto-close after 7 days of inactivity but resolved tickets are staying open indefinitely. I've double-checked the automation rule and it looks correct.", fromName: 'Helpdesk Admin', fromEmail: 'helpdesk.admin@autoclose.com', status: 'OPEN', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(3) },
  { subject: 'Can we get a custom contract for our Enterprise plan?', body: "We're a publicly listed company and our legal team requires a custom MSA (Master Service Agreement) before we can sign up for the Enterprise plan. Is this something you can accommodate?", fromName: 'Legal - PublicCo', fromEmail: 'legal@publicco.com', status: 'OPEN', category: 'GENERAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(1) },
  { subject: 'Timezone mismatch in scheduled reports', body: "Scheduled reports are running at the wrong time. I have the timezone set to EST (UTC-5) in my profile but reports are still running at UTC time. This affects our morning briefings.", fromName: 'Morning Reports User', fromEmail: 'morning.reports@timezone.com', status: 'RESOLVED', category: 'TECHNICAL_QUESTION', source: 'EMAIL', aiClassified: false, createdAt: daysAgo(6) },
  { subject: 'Refund for annual plan — company shutting down', body: "Unfortunately our company is shutting down and we no longer need the service. We are 4 months into our annual plan. Could you offer a pro-rated refund for the remaining 8 months?", fromName: 'Closing Down Co', fromEmail: 'admin@closingdownco.com', status: 'OPEN', category: 'REFUND_REQUEST', source: 'EMAIL', aiClassified: true, createdAt: daysAgo(2) },
  { subject: 'How to bulk update ticket statuses', body: "We have 200+ tickets that need to be marked as resolved. Is there a bulk action feature to update multiple ticket statuses at once, or do we need to do them one by one?", fromName: 'Cleanup Admin', fromEmail: 'cleanup.admin@bigteam.com', status: 'RESOLVED', category: 'GENERAL_QUESTION', source: 'MANUAL', aiClassified: false, createdAt: daysAgo(10) },
];

async function main() {
  console.log(`Inserting ${tickets.length} tickets...`);
  await prisma.ticket.createMany({ data: tickets });
  const total = await prisma.ticket.count();
  console.log(`Done. Total tickets in DB: ${total}`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
